services:
  frontend-library:
    image: node:21.6.2
    working_dir: /usr/src/app
    restart: no
    entrypoint: /usr/src/entrypoint.sh
    ports:
      - 80:5173
    volumes:
      - ./front/entrypoint.sh:/usr/src/entrypoint.sh
      - ./front/app:/usr/src/app
      - ./front/app/node_modules:/usr/src/app/node_modules
    depends_on:
      - backend-library
    environment:
      - API_URL=http://backend-library:8000

  backend-library:
    build:
      context: back/library
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./back/library/app:/app
    environment:
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=${MYSQL_HOST}
      - DB_PORT=${MYSQL_PORT}
      - DB_NAME=${MYSQL_DBNAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
